spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/weixin_sell_master?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell